import "package:flutter/material.dart";
import "package:bloco_na_rua/ui/core/tokens/app_colors.dart";

/// Light mode ColorScheme — Carnaval Sunset.
/// Primary: Violet #6D28D9 | Accent: Orange #F97316 | Secondary: Rose #FB7185
const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.primary,
  onPrimary: AppColors.textOnPrimary,
  primaryContainer: AppColors.primaryLight,
  onPrimaryContainer: AppColors.primaryDark,
  secondary: AppColors.secondary,
  onSecondary: AppColors.textOnPrimary,
  secondaryContainer: AppColors.secondaryLight,
  onSecondaryContainer: AppColors.secondaryDark,
  tertiary: AppColors.tertiary,
  onTertiary: AppColors.textOnPrimary,
  tertiaryContainer: AppColors.tertiaryContainerLight,
  onTertiaryContainer: AppColors.tertiary,
  error: AppColors.error,
  onError: AppColors.textOnPrimary,
  errorContainer: AppColors.errorContainerLight,
  onErrorContainer: AppColors.error,
  surface: AppColors.surfaceLight,
  surfaceContainerLowest: AppColors.backgroundLight,
  surfaceContainerLow: AppColors.surfaceVariantLight,
  surfaceContainer: AppColors.surfaceContainerLight,
  surfaceContainerHigh: AppColors.surfaceContainerHighLight,
  surfaceContainerHighest: AppColors.surfaceContainerHighestLight,
  onSurface: AppColors.textPrimary,
  onSurfaceVariant: AppColors.textSecondary,
  outline: AppColors.borderLight,
  outlineVariant: AppColors.surfaceVariantLight,
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: AppColors.textPrimary,
  onInverseSurface: AppColors.textOnPrimary,
  inversePrimary: AppColors.primaryLight,
);

/// Dark mode ColorScheme — Carnaval Sunset.
const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primaryLight,
  onPrimary: AppColors.primaryDark,
  primaryContainer: AppColors.primaryDark,
  onPrimaryContainer: AppColors.primaryLight,
  secondary: AppColors.secondaryLight,
  onSecondary: AppColors.secondaryDark,
  secondaryContainer: AppColors.secondaryDark,
  onSecondaryContainer: AppColors.secondaryLight,
  tertiary: AppColors.tertiary,
  onTertiary: AppColors.textOnPrimary,
  tertiaryContainer: AppColors.tertiaryContainerDark,
  onTertiaryContainer: AppColors.tertiaryContainerLight,
  error: AppColors.error,
  onError: AppColors.textOnPrimary,
  errorContainer: AppColors.errorContainerDark,
  onErrorContainer: AppColors.errorContainerLight,
  surface: AppColors.surfaceDark,
  onSurface: AppColors.textPrimaryDark,
  surfaceContainerHighest: AppColors.surfaceContainerDark,
  onSurfaceVariant: AppColors.textSecondaryDark,
  outline: AppColors.borderDark,
  outlineVariant: AppColors.surfaceVariantDark,
  shadow: Color(0xFF000000),
  scrim: Color(0xFF000000),
  inverseSurface: AppColors.textPrimaryDark,
  onInverseSurface: AppColors.textOnPrimary,
  inversePrimary: AppColors.primary,
);
