// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocyGKl3W0JWm1Bx8PIPRVnmUBvxs9wqE',
    appId: '1:78691265992:web:37afdaf1d5569da5fb64fd',
    messagingSenderId: '78691265992',
    projectId: 'bloco-na-rua',
    authDomain: 'bloco-na-rua.firebaseapp.com',
    storageBucket: 'bloco-na-rua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMa-fp_-6Y7-5tKfnVSJyM2w9b-zU8_1U',
    appId: '1:78691265992:android:d41cc19b0b6dc9affb64fd',
    messagingSenderId: '78691265992',
    projectId: 'bloco-na-rua',
    storageBucket: 'bloco-na-rua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FOEURxhvrheRVe9dZ7dS_ZcoRm20puY',
    appId: '1:78691265992:ios:f276ca4539b33c23fb64fd',
    messagingSenderId: '78691265992',
    projectId: 'bloco-na-rua',
    storageBucket: 'bloco-na-rua.appspot.com',
    iosBundleId: 'com.example.blocoNaRua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FOEURxhvrheRVe9dZ7dS_ZcoRm20puY',
    appId: '1:78691265992:ios:f276ca4539b33c23fb64fd',
    messagingSenderId: '78691265992',
    projectId: 'bloco-na-rua',
    storageBucket: 'bloco-na-rua.appspot.com',
    iosBundleId: 'com.example.blocoNaRua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDocyGKl3W0JWm1Bx8PIPRVnmUBvxs9wqE',
    appId: '1:78691265992:web:4bbb8856b7d13f79fb64fd',
    messagingSenderId: '78691265992',
    projectId: 'bloco-na-rua',
    authDomain: 'bloco-na-rua.firebaseapp.com',
    storageBucket: 'bloco-na-rua.appspot.com',
  );
}
